# Generated by Django 2.1.2 on 2018-12-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='click_nums',
            field=models.PositiveIntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
